// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqTyhkYFkiE7or4NBwzUyGOlilYJq8Q5Q',
    appId: '1:1019729526766:web:17da3a3951b4471c82d8ff',
    messagingSenderId: '1019729526766',
    projectId: 'fasum-aryadarmasaputra',
    authDomain: 'fasum-aryadarmasaputra.firebaseapp.com',
    storageBucket: 'fasum-aryadarmasaputra.firebasestorage.app',
    measurementId: 'G-TXPXXMWCQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZCRqzXbxtKs4vyfVU1X5sUfoI9x-JWks',
    appId: '1:1019729526766:android:7ff2146e684ab3d182d8ff',
    messagingSenderId: '1019729526766',
    projectId: 'fasum-aryadarmasaputra',
    storageBucket: 'fasum-aryadarmasaputra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEHvhXwiyAbJPGIGwo-ff6eZzVYU4aOmE',
    appId: '1:1019729526766:ios:a3882f524d4de4d882d8ff',
    messagingSenderId: '1019729526766',
    projectId: 'fasum-aryadarmasaputra',
    storageBucket: 'fasum-aryadarmasaputra.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEHvhXwiyAbJPGIGwo-ff6eZzVYU4aOmE',
    appId: '1:1019729526766:ios:a3882f524d4de4d882d8ff',
    messagingSenderId: '1019729526766',
    projectId: 'fasum-aryadarmasaputra',
    storageBucket: 'fasum-aryadarmasaputra.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqTyhkYFkiE7or4NBwzUyGOlilYJq8Q5Q',
    appId: '1:1019729526766:web:89edb230c7fe926782d8ff',
    messagingSenderId: '1019729526766',
    projectId: 'fasum-aryadarmasaputra',
    authDomain: 'fasum-aryadarmasaputra.firebaseapp.com',
    storageBucket: 'fasum-aryadarmasaputra.firebasestorage.app',
    measurementId: 'G-ZFC678QS70',
  );
}
